### ISSUE TITLE
Den Text kann man fast nicht lesen!

### ISSUE THREAD

**Issue by SBester001** [AlTrAugsburg/AlTr-Network#2]
https://github.com/AlTrAugsburg/AlTr-Network/blob/42ed49f7d354e04977f3178905c3ff43774322d4/README.txt#L2-L4

Es gibt doch bessere Möglichkeiten um das zu schreiben.
Zum Beispiel:

![altr-networks](https://user-images.githubusercontent.com/38667525/39369646-1cbcf628-4a3d-11e8-9a54-41aba773a614.PNG)

**Comment by SBester001** [comment]
Es gibt doch bessere Möglichkeiten um das zu schreiben.
Zum Beispiel:

![altr-networks](https://user-images.githubusercontent.com/38667525/39369646-1cbcf628-4a3d-11e8-9a54-41aba773a614.PNG)

**Comment by AlTrAugsburg** [comment]
Thanks for writing. I'm working on the problem and with the next update it will be fixed. The next update will take unfortunally some time, because the whole system will be changed, so stay tuned 😉

**Comment by AlTrAugsburg** [comment]
There's now a [README.md](https://github.com/AlTrAugsburg/AlTr-Network/blob/master/README.md). I hope it's now better.
